name: Run tests [Parallel] [Firefox][Chromium][Webkit]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Browsers
        run: python -m playwright install --with-deps

      - name: Run tests with Firefox
        run: |
          pytest --browser chromium --browser firefox --browser webkit --numprocesses auto --base-url https://www.ing.pl --video on --html test-results/report.html --self-contained-html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/